_BASE_: vitb_r101_384.yaml
MODEL:
  META_ARCHITECTURE: "CATSeg"
  SEM_SEG_HEAD:
    TEST_CLASS_JSON: "datasets/pc59.json"
    POOLING_SIZES: [1,1]
DATASETS:
  TEST: ("context_59_test_sem_seg",)
TEST:
  SLIDING_WINDOW: True