_BASE_: vitb_r101_384.yaml
MODEL:
  META_ARCHITECTURE: "CATSeg"
  SEM_SEG_HEAD:
    TEST_CLASS_JSON: "datasets/ade150.json"
    POOLING_SIZES: [1,1]
DATASETS:
  TEST: ("ade20k_150_test_sem_seg",)
TEST:
  SLIDING_WINDOW: True